// <auto-generated />
using System;
using GymWebApiBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymWebApiBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GymWebApiBackend.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("TeljesNev")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GymWebApiBackend.Models.Belepes", b =>
                {
                    b.Property<int>("BelepesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("belepes_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BelepesId"));

                    b.Property<DateTime>("BelepesIdopont")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("belepes_idopont");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    b.HasKey("BelepesId");

                    b.HasIndex("TagId");

                    b.ToTable("belepesek", (string)null);
                });

            modelBuilder.Entity("GymWebApiBackend.Models.Berlet", b =>
                {
                    b.Property<int>("BerletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("berlet_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BerletId"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("aktiv");

                    b.Property<int>("BerletTipusId")
                        .HasColumnType("int")
                        .HasColumnName("berlet_tipus_id");

                    b.Property<DateTime>("KezdetDatum")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("kezdet_datum");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    b.Property<DateTime>("VegeDatum")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("vege_datum");

                    b.HasKey("BerletId");

                    b.HasIndex("BerletTipusId");

                    b.HasIndex("TagId");

                    b.ToTable("berletek", (string)null);
                });

            modelBuilder.Entity("GymWebApiBackend.Models.BerletTipus", b =>
                {
                    b.Property<int>("BerletTipusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("berlet_tipus_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BerletTipusId"));

                    b.Property<decimal>("Ar")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("ar");

                    b.Property<int>("IdotartamNapok")
                        .HasColumnType("int")
                        .HasColumnName("idotartam_napok");

                    b.Property<string>("Megnevezes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("megnevezes");

                    b.HasKey("BerletTipusId");

                    b.ToTable("berlettipusok", (string)null);
                });

            modelBuilder.Entity("GymWebApiBackend.Models.Szekreny", b =>
                {
                    b.Property<int>("SzekrenyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("szekreny_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SzekrenyId"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("aktiv");

                    b.Property<int>("SzekrenySzam")
                        .HasColumnType("int")
                        .HasColumnName("szekreny_szam");

                    b.HasKey("SzekrenyId");

                    b.ToTable("szekrenyek", (string)null);
                });

            modelBuilder.Entity("GymWebApiBackend.Models.SzekrenyFoglalas", b =>
                {
                    b.Property<int>("FoglalasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("foglalas_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FoglalasId"));

                    b.Property<DateTime>("FoglalvaKezdete")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("foglalva_kezdete");

                    b.Property<DateTime>("FoglalvaVege")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("foglalva_vege");

                    b.Property<int>("SzekrenyId")
                        .HasColumnType("int")
                        .HasColumnName("szekreny_id");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    b.Property<bool>("Zarva")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("zarva");

                    b.HasKey("FoglalasId");

                    b.HasIndex("SzekrenyId");

                    b.HasIndex("TagId");

                    b.ToTable("szekreny_foglalasok", (string)null);
                });

            modelBuilder.Entity("GymWebApiBackend.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TagId"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("aktiv");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("longtext")
                        .HasColumnName("identity_user_id");

                    b.Property<string>("Keresztnev")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("keresztnev");

                    b.Property<DateTime>("SzuletesiDatum")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("szuletesi_datum");

                    b.Property<string>("Vezeteknev")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("vezeteknev");

                    b.HasKey("TagId");

                    b.ToTable("tagok", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GymWebApiBackend.Models.Belepes", b =>
                {
                    b.HasOne("GymWebApiBackend.Models.Tag", "Tag")
                        .WithMany("Belepesek")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("GymWebApiBackend.Models.Berlet", b =>
                {
                    b.HasOne("GymWebApiBackend.Models.BerletTipus", "BerletTipus")
                        .WithMany("Berletek")
                        .HasForeignKey("BerletTipusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymWebApiBackend.Models.Tag", "Tag")
                        .WithMany("Berletek")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BerletTipus");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("GymWebApiBackend.Models.SzekrenyFoglalas", b =>
                {
                    b.HasOne("GymWebApiBackend.Models.Szekreny", "Szekreny")
                        .WithMany("SzekrenyFoglalasok")
                        .HasForeignKey("SzekrenyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymWebApiBackend.Models.Tag", "Tag")
                        .WithMany("SzekrenyFoglalasok")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Szekreny");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GymWebApiBackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GymWebApiBackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymWebApiBackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GymWebApiBackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymWebApiBackend.Models.BerletTipus", b =>
                {
                    b.Navigation("Berletek");
                });

            modelBuilder.Entity("GymWebApiBackend.Models.Szekreny", b =>
                {
                    b.Navigation("SzekrenyFoglalasok");
                });

            modelBuilder.Entity("GymWebApiBackend.Models.Tag", b =>
                {
                    b.Navigation("Belepesek");

                    b.Navigation("Berletek");

                    b.Navigation("SzekrenyFoglalasok");
                });
#pragma warning restore 612, 618
        }
    }
}
